export const KA_PRODUCT_NAME = "kubearmor";
export const KA_NAME = "kubearmor";
export * from './types/artifacthub';
export * from './types/core';
export * from './types/catalog.cattle.io.app';
export * from './types/chart';
export * from './types/grafana';
export * from './types/kubewarden';
export * from './types/jaeger';
export * from './types/metrics';
export * from './types/policy';
export * from './types/policy-reporter';
export * from './types/rancher';
export * from './types/service';
export * from './types/wgpolicyk8s.io';